export const TYPE_COLORS: Record<string, { bg: string; text: string }> = {
  normal:   { bg: "bg-stone-400",   text: "text-white" },
  fire:     { bg: "bg-orange-500",  text: "text-white" },
  water:    { bg: "bg-blue-500",    text: "text-white" },
  electric: { bg: "bg-yellow-400",  text: "text-gray-900" },
  grass:    { bg: "bg-green-500",   text: "text-white" },
  ice:      { bg: "bg-cyan-400",    text: "text-gray-900" },
  fighting: { bg: "bg-red-700",     text: "text-white" },
  poison:   { bg: "bg-purple-500",  text: "text-white" },
  ground:   { bg: "bg-amber-600",   text: "text-white" },
  flying:   { bg: "bg-indigo-400",  text: "text-white" },
  psychic:  { bg: "bg-pink-500",    text: "text-white" },
  bug:      { bg: "bg-lime-500",    text: "text-white" },
  rock:     { bg: "bg-stone-600",   text: "text-white" },
  ghost:    { bg: "bg-violet-700",  text: "text-white" },
  dragon:   { bg: "bg-indigo-700",  text: "text-white" },
  dark:     { bg: "bg-gray-800",    text: "text-white" },
  steel:    { bg: "bg-slate-500",   text: "text-white" },
  fairy:    { bg: "bg-pink-300",    text: "text-gray-900" },
};

export const TYPE_BG_CARD: Record<string, string> = {
  normal:   "bg-stone-100",
  fire:     "bg-orange-50",
  water:    "bg-blue-50",
  electric: "bg-yellow-50",
  grass:    "bg-green-50",
  ice:      "bg-cyan-50",
  fighting: "bg-red-50",
  poison:   "bg-purple-50",
  ground:   "bg-amber-50",
  flying:   "bg-indigo-50",
  psychic:  "bg-pink-50",
  bug:      "bg-lime-50",
  rock:     "bg-stone-100",
  ghost:    "bg-violet-50",
  dragon:   "bg-indigo-50",
  dark:     "bg-gray-100",
  steel:    "bg-slate-50",
  fairy:    "bg-pink-50",
};
